# Generated by Django 3.2.18 on 2023-04-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='select1_user',
            new_name='select1_users',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='select2_user',
            new_name='select2_users',
        ),
    ]
