# Generated by Django 3.2.18 on 2023-04-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230420_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images1/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images2/'),
        ),
    ]
