# Generated by Django 3.2.18 on 2023-03-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_newspaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newspaper',
        ),
    ]
